name: readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *' # every 1 hr

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Update README.md
      run: |
        python event.py > README.md
        cat README.md # debug

    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Nathachai Thongniran
        author_email: inid3a@gmail.com
        message: "bot: update README.md file"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
